# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024 Robin Jarry
---
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: l
      CC: gcc-14
    steps:
      - name: install system dependencies
        run: |
          set -xe
          sudo apt-get update -qy
          sudo apt-get install -qy --no-install-recommends \
            doxygen \
            gcc \
            libasan8 \
            libc-dev \
            libedit-dev \
            libreadline-dev \
            libyaml-dev \
            meson \
            ninja-build \
            pkg-config
      - uses: actions/checkout@v4
      - run: |
          meson setup build \
            --auto-features=enabled \
            -Db_sanitize=address
      - run: ninja -C build
      - run: build/test/ecoli-test
